### This is a sample Vagrant file, please modify it to suit your configurations
$script_inject_pk =<<-'SCRIPT'
cat /vagrant/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
SCRIPT

Vagrant.configure("2") do |configuration|
  #configuration.vm.network "public_network", ip: "192.168.0.17"

  configuration.vm.define "jenkins" do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.hostname = "jenkins.local"
    config.vm.network "private_network", ip: "192.168.56.10"
    config.vm.network "forwarded_port", guest: 8080, host: 8081
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
       vb.cpus = "2"
     end
   end

  configuration.vm.define "tomcat_server" do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.hostname = "tomcat.local"
    config.vm.network "private_network", ip: "192.168.56.20"
    config.vm.network "forwarded_port", guest: 8080, host: 8082
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
       vb.cpus = "1"
     end
   end

  configuration.vm.define "prometheus" do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.hostname = "prometheus.local"
    config.vm.network "private_network", ip: "192.168.56.30"
    config.vm.network "forwarded_port", guest: 8080, host: 8083
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
    end
  end


  configuration.vm.define "kubernetes" do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.hostname = "kubernetes.local"
    config.vm.network "private_network", ip: "192.168.56.40"
    config.vm.network "forwarded_port", guest: 8080, host: 8084
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = "2"
    end
  end
end
